### ISSUE TITLE
pdflatex.exe won't run

### ISSUE THREAD

**Issue by aburns2293** [marclos/UAV#3]
When I try to compile the Raspberry_Pi_Guide.rnw document, it gets stuck in a loop of trying to run the pdflatex.exe program.  It never pops an error, it just runs continuously (for hours) and the only way to stop the document or leave R is to restart my computer.  I think this might have something to do with downloading Miktex (and then undownloading it) that messed up the program.

Other files still knit.  I am in the knitr mode  (not Sweave), and changed the lines in the document that were added to support Sweave when I temporarily tried that by reverting to an earlier version.  Most of the info online has to do with specific errors with pdflatex.exe, not with the program getting stuck loading.  I gave up after several hours of fighting with it.

**Comment by marclos** [comment]
Bummer. Okay, I think you’ll need to remove all the latex programs and reinstall.

Marc


Marc Los Huertos
Associate Professor, Environmental Analysis
🌏 5C EA Statement Against Systemic Racism<https://docs.google.com/document/d/1KtpUYnJibJfsyJAMkHSHNYhKMXURY8aDaszgIMCdtT8/edit?usp=sharing>

Office:
Seeley G. Mudd, Room 106B
Pomona College
(909) 607-7787

Mail:
Environmental Analysis Program
Seeley G. Mudd, Pomona College
640 N College Ave, Rm. 106C
Claremont CA 91711-7003

**Comment by marclos** [comment]
Delete listings.sty
